## Course data paths

Run the setup cell below before the lesson. Bundled inputs are resolved from the course repository, so paths also work after moving the notebook into `code/`. Generated practice files still use the notebook working directory.


In [ ]:
from pathlib import Path

# Find the cloned course repository from the notebook or repository folder.
COURSE_ROOT = next(
    (folder for folder in (Path.cwd(), *Path.cwd().parents)
     if (folder / "docs" / "course-catalog.json").is_file()),
    None,
)
if COURSE_ROOT is None:
    raise FileNotFoundError("Open this notebook inside the cloned course repository.")


# Day 4 — NumPy: Data Loading & Saving | Indexing | Broadcasting | Type Casting | Arithmetic | Universal Functions
**R.A: Muhammad Huzifa**

In [ ]:
import numpy as np

---
## 1. Data Loading & Saving
**`np.save()` stores a NumPy array to disk; `np.load()` reads it back.**

In [ ]:
import numpy as np

arr = np.arange(12).reshape(3, 4)
print(arr)
np.save('my_array.npy', arr)     
     # File extension .npy is added automatically if missing

arr2=np.arange(16).reshape(4,4)
np.save('numpy.npy',arr2)

loaded=np.load('numpy.npy')
print(loaded)


In [ ]:
loaded = np.load('my_array.npy')
print(loaded)
# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]]

### Multiple

In [ ]:
a = np.array([1, 2, 3])
b = np.array([[4, 5], [6, 7]])
np.savez('multi.npz', array1=a, array2=b)   # You can provide keyword names

In [ ]:
# data = np.load('multi.npz')
# print(data.files)            # ['array1', 'array2']
# print(data['array1'])        # [1 2 3]
# print(data['array2'])        # [[4 5] [6 7]]


data1=np.arange(11)
data2=np.arange(1.100)
np.savez('muhammadabid.npz',key1=data1,key2=data2)
load=np.load('muhammadabid.npz')
print(load.files)
print(load['key1'])
print(load['key2'])



In [ ]:
np.savez_compressed('multi_comp.npz', a=a, b=b)

#### np.savetxt() – Save a 1D or 2D array to a text file


In [ ]:
import numpy as np
arr2d = np.array([[1.5, 2.3, 3.9], [4.2, 5.1, 6.7]])
np.savetxt('data.csv', arr2d, delimiter=',', header='x,y,z', comments='')


arr3=np.arange(1,10)
np.savetxt('abid.csv',arr3, delimiter=',', header='abid xd' ,comments='')
loaded=np.loadtxt('abid.csv',delimiter=',' , skiprows=1)


In [ ]:
loaded = np.loadtxt('data.csv', delimiter=',', skiprows=1)
print(loaded)
# [[1.5 2.3 3.9]
#  [4.2 5.1 6.7]]

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
np.save('my_array.npy', arr)


In [ ]:
loaded = np.load('my_array.npy')
print(loaded)

In [ ]:
data = np.loadtxt(COURSE_ROOT / "modules/02-numpy/datasets/Book1.csv", delimiter=",")
print(data)

In [ ]:
data = np.loadtxt(COURSE_ROOT / "modules/02-numpy/datasets/Book1.csv", delimiter=",", skiprows=1)
print(data)

In [ ]:
data = np.genfromtxt(COURSE_ROOT / "modules/02-numpy/datasets/Book1.csv", delimiter=",")
print(data)

**`np.savetxt()` saves to CSV; `np.loadtxt()` reads it back.**

In [ ]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.savetxt('matrix.csv', matrix, delimiter=',')

In [ ]:

loaded_csv = np.loadtxt('matrix.csv', delimiter=',')
print(loaded_csv)

In [ ]:
np.isnan(loaded_csv)

**Practice 1 — Save & Load**

In [ ]:
scores = np.array([88, 75, 92, 60, 45])
np.save('scores.npy', scores)
result = np.load('scores.npy')
print('Loaded scores:', result)

In [ ]:
prices = np.array([[100, 200], [300, 400], [500, 600]])
np.savetxt('prices.csv', prices, delimiter=',')


In [ ]:
loaded_prices = np.loadtxt('prices.csv', delimiter=',')
print('Loaded prices:\n', loaded_prices)

#### ✏️ Exercises — Data Loading & Saving

In [ ]:
# Exercise 1
# Create an array of 6 temperatures [36.5, 37.0, 38.2, 36.8, 39.1, 37.5]
# Save it as 'temperatures.npy'
# Load it back and print it

import numpy as np
temp=np.arange(30,40,0.5)
np.save('temp.npy',temp)
load=np.load('temp.npy',)
print(load)


# 1. Array banayein (Floats mein hi banaygi kyunki step 0.5 hai)
temp = np.arange(30, 40, 0.5)

# 2. Save karein (Filename aur Array dono batana zaroori hai)
np.save('temp.npy', temp)

# 3. Load karein (np. prefix ke saath)
load_data = np.load('temp.npy')

# 4. Print karke check karein
print("Loaded Array:", load_data)
print("Original Array:", temp)

# YOUR CODE HERE


In [ ]:
# Exercise 2
# Create a 3x3 array of student marks (any values you choose)
# Save it as 'marks.csv' using savetxt with comma delimiter
# Load it back and print it
import numpy as np

# 1. 3x3 Array banana (Floats ke saath)
# Aap direct 2D list de sakte hain, reshape ki zaroorat nahi padegi
marks = np.array([
    [85.5, 90.0, 78.5],
    [70.0, 88.5, 92.0],
    [95.0, 82.5, 89.0]
], dtype=float)

# 2. CSV file mein save karna
# Yaad rakhein: np.savetxt kuch return nahi karta, bas file save karta hai
np.savetxt('marks.csv', marks, header='Sub1,Sub2,Sub3', delimiter=',', comments='')



# 3. CSV file se load karna
# skiprows=1 isliye taake header (Sub1, Sub2, Sub3) ko ignore kiya ja sake
load_data = np.loadtxt('marks.csv', delimiter=',', skiprows=1)

# 4. Result print karna

# Agar aap check karna chahein ke float hai ya nahi:



In [ ]:
# Exercise 3
# Save two arrays in one file using np.savez()
# Array 1: names_ids = [101, 102, 103]
# Array 2: gpa       = [3.5, 3.8, 2.9]
# Load and print both arrays from the .npz file

# YOUR CODE HERE


In [ ]:
# Exercise 4
# Create an array: monthly_sales = [4500, 6700, 3200, 8900, 7600, 5100]
# Save it as 'sales.npy'
# Load it and print the maximum and minimum sales value

# YOUR CODE HERE


---
## 2. NumPy Indexing & Selection
**Accessing elements, rows, and columns from arrays by position or condition.**

In [ ]:
arr2d = np.array([[10, 20, 30],
                  [40, 50, 60],
                  [70, 80, 90]])

print('Single element:', arr2d[1, 1])
print('Full row 0:    ', arr2d[0])
print('Full col 2:    ', arr2d[:, 2])
print('Sub-array:\n',    arr2d[0:2, 0:2])

In [ ]:
B = np.array([
[11,22,33,44],
[55,66,77,88],
[99,110,121,132]
])
B[0]

In [ ]:
C = np.array([
[3,6,9],
[12,15,18],
[21,24,27]
])
C[:,1]

In [ ]:
D = np.array([
[10,20,30,40],
[50,60,70,80],
[90,100,110,120]
])

D[0:2,1:3]

**Logical (Boolean) Selection — filter by condition.**

In [ ]:
grades = np.array([45, 78, 62, 90, 33, 88])
print('Pass (>=50):', grades[grades >= 50])
print('Fail (<50): ', grades[grades < 50])

**Practice 1 — Indexing**

In [ ]:
seats = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

print('Seat [1][2]:', seats[1, 2])
print('Row 2:      ', seats[2])
print('Col 0:      ', seats[:, 0])
print('Block [0:2, 1:3]:\n', seats[0:2, 1:3])

In [ ]:
temps = np.array([28, 35, 22, 40, 18, 36, 29])
print('Hot (>30):', temps[temps > 30])
print('Cold (<25):', temps[temps < 25])

In [ ]:
E = np.array([
[1,2,3,4],
[5,6,7,8],
[9,10,11,12]
])

E[:, ::2]

In [ ]:
F = np.array([
[100,200,300],
[400,500,600],
[700,800,900]
])

F[-1]

In [ ]:
G = np.array([
[12,45,60],
[75,20,30],
[90,15,55]
])

G[G > 50]

In [ ]:
H = np.array([
[4,7,9],
[10,13,16],
[21,22,25]
])

H[H % 2 == 0]

#### Fancy Indexing

In [ ]:
J = np.array([
[1,3,5],
[7,9,11],
[13,15,17],
[19,21,23]
])

J[[1],[2]]

In [ ]:
K = np.array([
[10,20,30],
[40,50,60],
[70,80,90]
])

K[[0,2],[1,2]]

In [ ]:
L = np.array([
[2,4,6,8],
[10,12,14,16],
[18,20,22,24]
])

L[:,[0,3]]

In [ ]:
import numpy as np

A = np.array([
[
[1,2,3],
[4,5,6]
],
[
[7,8,9],
[10,11,12]
]
])
# A.shape
A[1,0,2]

In [ ]:
B = np.array([
[
[10,20],
[30,40]
],
[
[50,60],
[70,80]
],
[
[90,100],
[110,120]
]
])

B[1]

In [ ]:
C = np.array([
[
[2,4,6],
[8,10,12]
],
[
[14,16,18],
[20,22,24]
]
])

C[:,:,1]

In [ ]:
D = np.array([
[
[5,10,15],
[20,25,30]
],
[
[35,40,45],
[50,55,60]
]
])

D[:,1,:]

In [ ]:
E = np.array([
[
[3,6,9,12],
[15,18,21,24]
],
[
[27,30,33,36],
[39,42,45,48]
]
])

E[:,:,1:3]

#### ✏️ Exercises — Indexing & Selection

In [ ]:
# Exercise 1
# Create this 4x4 array:
# [[1,  2,  3,  4],
#  [5,  6,  7,  8],
#  [9,  10, 11, 12],
#  [13, 14, 15, 16]]
# a) Print element at row 3, col 2
# b) Print the entire 2nd row
# c) Print the entire 3rd column
# d) Print the 2x2 bottom-right sub-array

# YOUR CODE HERE


In [ ]:
# Exercise 2
# prices = [150, 80, 320, 45, 500, 260, 99]
# a) Select all prices above 200
# b) Select all prices between 50 and 300 (use & operator)
# c) Count how many items cost less than 100

# YOUR CODE HERE


In [ ]:
# Exercise 3
# Create array: exam = [[55,70,80],[40,90,65],[30,75,85]]
# a) Get the score of student 2, subject 1
# b) Get all scores of student 0 (row 0)
# c) Get all scores for subject 2 (col 2)
# d) Using logical selection, find which scores in the full array are >= 70

# YOUR CODE HERE


In [ ]:
# Exercise 4
# sales = [1200, 450, 890, 2300, 670, 1800, 300, 950]
# a) Select sales above the average (use np.mean)
# b) Replace all sales below 500 with 0 (use boolean assignment)
# c) Print the modified array

# YOUR CODE HERE


---
## 3. Broadcasting
**NumPy automatically expands smaller arrays to match bigger ones during operations.**

In [ ]:
arr = np.array([1, 2, 3, 4])
print('Array + 10:  ', arr + 10)
print('Array * 3:   ', arr * 3)
print('Array ** 2:  ', arr ** 2)

In [ ]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
row    = np.array([10, 20, 30])

print('Matrix + row:\n', matrix + row)
print('Matrix shapes:', matrix.shape, '+', row.shape)

#### Scalar

In [ ]:
M = np.array([
[1,2],
[3,4],
[5,6]
])

M + 5

##### Row Vector

In [ ]:
N = np.array([
[10,20,30],
[40,50,60]
])
v = np.array([1,2,3])

N + v

#### Column Broadcasting

In [ ]:
P = np.array([
[2,4,6],
[8,10,12],
[14,16,18]
])

v = np.array([[1],[2],[3]])

P + v

**Practice 1 — Broadcasting**

In [ ]:
import numpy as np

row = np.array([[1, 2, 3]])
col = np.array([[10],
                [20],
                [30]])


addition = row + col
print("Addition (row + col):")
print(addition)
multiplication = row * col
print("Multiplication (row * col) - Outer Product:")
print(multiplication)


In [ ]:
raw_scores = np.array([55, 60, 70, 80, 45])
bonus = 5
adjusted = raw_scores + bonus
print('Original:', raw_scores)
print('With bonus:', adjusted)

In [ ]:
C = np.array([
[1,2],
[3,4],
[5,6]
])

v = np.array([
[10],
[20],
[30]])

C.shape , v.shape

In [ ]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])    # shape (3, 3)

b = np.array([[10],
              [20],
              [30]])          # shape (3, 1)

result = a * b                 # element-wise multiplication
print(result)
# [[10 20 30]
#  [80 100 120]
#  [210 240 270]]

In [ ]:
a = np.random.randint(0, 10, size=(2, 3, 4))   # shape (2,3,4)
b = np.random.randint(0, 10, size=(3, 4))      # shape (3,4)

result = a + b
print("a shape:", a.shape)
print("b shape:", b.shape)
print("result shape:", result.shape)           # (2,3,4)

In [ ]:
import numpy as np

A = np.array([2,4,6])
B = np.array([3,5,7])

result = A * B

print("Array A:",A)
print("Array B:",B)
print("Result:",result)

In [ ]:
import numpy as np

matrix = np.array([
[1,2,3],
[4,5,6]
])

scalar = 10

result = matrix * scalar

print("Matrix:\n",matrix)
print("Scalar:",scalar)
print("Result:\n",result)

In [ ]:
D = np.array([
[[1,2],[3,4]],
[[5,6],[7,8]]
])
v = np.array([10,20])

D * v

In [ ]:
import numpy as np

matrix = np.array([
[1,2,3],
[4,5,6],
[7,8,9]
])

vector = np.array([10,20,30])

result = matrix * vector

print("Matrix:\n",matrix)
print("Vector:",vector)
print("Result:\n",result)

In [ ]:
import numpy as np

matrix = np.array([
[2,4],
[6,8],
[10,12]
])

column_vector = np.array([
[3],
[5],
[7]
])

result = matrix * column_vector

print("Matrix:\n",matrix)
print("Column Vector:\n",column_vector)
print("Result:\n",result)

In [ ]:
import numpy as np

matrix = np.array([
[2,4],
[6,8],
[10,12]
])

column_vector = np.array([
[3],
[5],
[7]
])

result = matrix * column_vector

print("Matrix:\n",matrix)
print("Column Vector:\n",column_vector)
print("Result:\n",result)

In [ ]:
import numpy as np

tensor = np.array([
[
[1,2],
[3,4]
],
[
[5,6],
[7,8]
]
])

vector = np.array([10,20])

result = tensor * vector

print("Tensor:\n",tensor)
print("Vector:",vector)
print("Result:\n",result)

In [ ]:
import numpy as np

dataset = np.array([
[10,20,30],
[40,50,60],
[70,80,90]
])

scale = np.array([1,10,100])

result = dataset * scale

print("Dataset:\n",dataset)
print("Scale Vector:",scale)
print("Result:\n",result)

### Error

In [ ]:
import numpy as np

A = np.array([
[1,2,3],
[4,5,6]
])

B = np.array([10,20,30,40])

result = A * B

#### ✏️ Exercises — Broadcasting

In [ ]:
# Exercise 1
# base_salary = [30000, 45000, 60000, 25000]
# Add a 10% raise to all salaries using broadcasting (multiply by 1.1)
# Print original and new salaries

# YOUR CODE HERE


In [ ]:
# Exercise 2
# product_prices = [[100, 200, 300], [400, 500, 600]]
# discount = [10, 20, 30]  (discount per column/category)
# Subtract discount from each row of prices using broadcasting
# Print the discounted prices

# YOUR CODE HERE


In [ ]:
# Exercise 3
# celsius = [0, 10, 20, 30, 37, 100]
# Convert all to Fahrenheit using broadcasting: F = (C * 9/5) + 32
# Print both arrays

# YOUR CODE HERE


In [ ]:
# Exercise 4
# distance_km = [[5, 10, 15], [20, 25, 30]]
# speed_kmph  = [50, 60, 80]  (one speed per column)
# Calculate time (hours) = distance / speed using broadcasting
# Print the time matrix

# YOUR CODE HERE


---
## 4. Type Casting
**`.astype()` converts array elements from one data type to another.**

In [ ]:
float_arr = np.array([1.9, 2.7, 3.3, 4.8])
int_arr   = float_arr.astype(int)
print('float:', float_arr)
print('int:  ', int_arr)

In [ ]:
int_arr2   = np.array([1, 0, 1, 0, 1])
bool_arr   = int_arr2.astype(bool)
float_arr2 = int_arr2.astype(float)
print('int:  ', int_arr2)
print('bool: ', bool_arr)
print('float:', float_arr2)

**Practice 1 — Type Casting**

In [ ]:
sensor_readings = np.array([98.6, 101.2, 99.8, 103.5])
print('dtype before:', sensor_readings.dtype)
as_int = sensor_readings.astype(np.int32)
print('as int32:', as_int)

In [ ]:
flags = np.array([1, 0, 0, 1, 1, 0])
as_bool = flags.astype(bool)
print('flags as bool:', as_bool)
print('sum of True:', np.sum(as_bool))

#### ✏️ Exercises — Type Casting

In [ ]:
# Exercise 1
# weights = [55.7, 72.3, 68.9, 80.1, 61.4]
# a) Print the dtype
# b) Cast to int32 and print
# c) Cast to float16 and print

# YOUR CODE HERE


In [ ]:
# Exercise 2
# votes = [1, 0, 1, 1, 0, 0, 1]  (1=yes, 0=no)
# a) Cast to bool and print
# b) Count total 'yes' votes using np.sum()
# c) Cast the bool array back to int and print

# YOUR CODE HERE


In [ ]:
# Exercise 3
# prices_str = np.array(['10.5', '20.0', '30.75', '15.25'])  dtype is string
# a) Cast to float64 and print
# b) Cast that float array to int and print (observe the truncation)

# YOUR CODE HERE


In [ ]:
# Exercise 4
# exam_marks = [45.9, 78.3, 92.7, 33.1, 60.5]
# a) Cast to int (observe what happens to decimals)
# b) Use np.round() first, THEN cast to int
# c) Print both and explain the difference

# YOUR CODE HERE


---
## 5. Arithmetic Operations
**Element-wise: add, subtract, multiply, divide, exponentiation.**

In [ ]:
a = np.array([10, 20, 30, 40])
b = np.array([1,  2,  3,  4 ])

print('Add:        ', a + b)
print('Subtract:   ', a - b)
print('Multiply:   ', a * b)
print('Divide:     ', a / b)
print('Exponent:   ', b ** 3)

In [ ]:
income   = np.array([50000, 75000, 30000, 90000])
expenses = np.array([20000, 40000, 15000, 60000])

savings      = income - expenses
savings_pct  = (savings / income) * 100
print('Savings:    ', savings)
print('Savings %:  ', savings_pct)

**Practice 1 — Arithmetic**

In [ ]:
units_sold = np.array([5, 3, 8, 2, 10])
price_each = np.array([200, 500, 150, 1000, 50])
revenue    = units_sold * price_each
discount   = revenue * 0.1
final_rev  = revenue - discount
print('Revenue:   ', revenue)
print('Discount:  ', discount)
print('Final Rev: ', final_rev)

In [ ]:
sides = np.array([2.0, 3.5, 5.0, 7.2, 4.0])
areas = sides ** 2
print('Sides:', sides)
print('Areas:', areas)

#### ✏️ Exercises — Arithmetic Operations

In [ ]:
# Exercise 1
# students = 5 students with marks in 3 subjects each (create a 5x3 array)
# Calculate total marks per student (use np.sum with axis=1)
# Calculate average marks per student

# YOUR CODE HERE


In [ ]:
# Exercise 2
# initial_investment = [1000, 2000, 5000, 800]
# annual_return_rate = [0.08, 0.12, 0.05, 0.15]
# Calculate value after 1 year: value = investment * (1 + rate)
# Calculate profit = value - initial_investment

# YOUR CODE HERE


In [ ]:
# Exercise 3
# speed_ms = [10, 25, 5, 18, 30]  (meters per second)
# Convert to km/h: multiply by 3.6
# Find: max speed, min speed, average speed in km/h

# YOUR CODE HERE


In [ ]:
# Exercise 4
# A = [[2,3],[4,5]]   B = [[1,2],[3,4]]
# a) Element-wise multiply A * B
# b) Element-wise A ** 2
# c) np.dot(A, B) — matrix multiplication (observe the difference)

# YOUR CODE HERE


---
## 6. Universal Array Functions (ufuncs)
**Built-in math functions that operate on entire arrays: sqrt, exp, sin, log, max, etc.**

In [ ]:
arr = np.array([1, 4, 9, 16, 25])
print('sqrt:', np.sqrt(arr))
print('max: ', np.max(arr))
print('min: ', np.min(arr))
print('sum: ', np.sum(arr))
print('mean:', np.mean(arr))

In [ ]:
angles = np.array([0, np.pi/6, np.pi/4, np.pi/2])
print('sin:', np.round(np.sin(angles), 2))
print('cos:', np.round(np.cos(angles), 2))

x = np.array([0, 1, 2, 3])
print('exp:', np.round(np.exp(x), 3))
print('log:', np.round(np.log(np.exp(x)), 3))

**Practice 1 — Universal Functions**

In [ ]:
areas = np.array([4.0, 9.0, 16.0, 25.0, 36.0])
sides = np.sqrt(areas)
print('Area  → Side')
for a, s in zip(areas, sides):
    print(f'  {a:.1f}  → {s:.1f}')

In [ ]:
temperatures = np.array([-5, 0, 15, 22, 35, 42, -10, 8])
print('Max temp:   ', np.max(temperatures))
print('Min temp:   ', np.min(temperatures))
print('Mean temp:  ', np.mean(temperatures))
print('Abs values: ', np.abs(temperatures))

#### ✏️ Exercises — Universal Functions

In [ ]:
# Exercise 1
# hypotenuse: for a right triangle, c = sqrt(a^2 + b^2)
# a_sides = [3, 5, 8, 6]
# b_sides = [4, 12, 15, 8]
# Calculate all hypotenuses using np.sqrt()

# YOUR CODE HERE


In [ ]:
# Exercise 2
# population = [100, 200, 400, 800, 1600]  (doubles each step)
# a) Apply np.log2() to find doubling steps
# b) Apply np.log() (natural log) and print
# c) What is np.exp(np.log(population))? Print and explain.

# YOUR CODE HERE


In [ ]:
# Exercise 3
# exam_scores = [[45, 78, 92], [33, 88, 61], [70, 55, 80]]
# a) Find max score in each row (axis=1)
# b) Find min score in each column (axis=0)
# c) Find overall mean
# d) Find standard deviation using np.std()

# YOUR CODE HERE


In [ ]:
# Exercise 4
# Implement the Sigmoid function (used in neural networks): sigmoid = 1 / (1 + np.exp(-x))
# x = [-3, -1, 0, 1, 3]
# a) Compute sigmoid for all values using np.exp()
# b) Print rounded to 3 decimal places
# c) What do you observe about the output range?

# YOUR CODE HERE
