In [1]:
# Create an array of 6 temperatures [36.5, 37.0, 38.2, 36.8, 39.1, 37.5]
# Save it as 'temperatures.npy'
# Load it back and print it

import numpy as np

temperatures = np.array([36.5, 37.0, 38.2, 36.8, 39.1, 37.5])
np.save('temperatures.npy', temperatures)
loaded_temps = np.load('temperatures.npy')
print("Loaded temperatures:", loaded_temps)

Loaded temperatures: [36.5 37.  38.2 36.8 39.1 37.5]


In [2]:
# Create a 3x3 array of student marks (any values you choose)
# Save it as 'marks.csv' using savetxt with comma delimiter
# Load it back and print it

import numpy as np

# 3x3 marks array (3 students, 3 subjects)
marks = np.array([
    [85.5, 90.0, 78.5],
    [70.0, 88.5, 92.0],
    [95.0, 82.5, 89.0]
])

np.savetxt('marks.csv', marks, delimiter=',', header='Math,Physics,Chemistry', comments='')
loaded_marks = np.loadtxt('marks.csv', delimiter=',', skiprows=1)
print("Loaded marks:\n", loaded_marks)

Loaded marks:
 [[85.5 90.  78.5]
 [70.  88.5 92. ]
 [95.  82.5 89. ]]


In [3]:
# Save two arrays in one file using np.savez()
# Array 1: names_ids = [101, 102, 103]
# Array 2: gpa = [3.5, 3.8, 2.9]
# Load and print both arrays from the .npz file

import numpy as np

names_ids = np.array([101, 102, 103])
gpa = np.array([3.5, 3.8, 2.9])

np.savez('student_data.npz', student_ids=names_ids, student_gpa=gpa)

loaded_data = np.load('student_data.npz')
print("Loaded IDs:", loaded_data['student_ids'])
print("Loaded GPAs:", loaded_data['student_gpa'])

Loaded IDs: [101 102 103]
Loaded GPAs: [3.5 3.8 2.9]


In [1]:
# Create an array: monthly_sales = [4500, 6700, 3200, 8900, 7600, 5100]
# Save it as 'sales.npy'
# Load it and print the maximum and minimum sales value

import numpy as np

monthly_sales = np.array([4500, 6700, 3200, 8900, 7600, 5100])
np.save('sales.npy', monthly_sales)

loaded_sales = np.load('sales.npy')
print("Maximum sales:", np.max(loaded_sales))
print("Minimum sales:", np.min(loaded_sales))

Maximum sales: 8900
Minimum sales: 3200


In [2]:
# Create this 4x4 array:
# [[1, 2, 3, 4],
#  [5, 6, 7, 8],
#  [9, 10, 11, 12],
#  [13, 14, 15, 16]]
# a) Print element at row 3, col 2
# b) Print the entire 2nd row
# c) Print the entire 3rd column
# d) Print the 2x2 bottom-right sub-array

import numpy as np

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

print("Element at row 3, col 2:", arr[3, 2])      # Note: 0-indexed, so row3 is index 3
print("Entire 2nd row:", arr[1])                   # row index 1
print("Entire 3rd column:", arr[:, 2])            # column index 2
print("2x2 bottom-right sub-array:\n", arr[2:4, 2:4])

Element at row 3, col 2: 15
Entire 2nd row: [5 6 7 8]
Entire 3rd column: [ 3  7 11 15]
2x2 bottom-right sub-array:
 [[11 12]
 [15 16]]


In [3]:
# prices = [150, 80, 320, 45, 500, 260, 99]
# a) Select all prices above 200
# b) Select all prices between 50 and 300 (use & operator)
# c) Count how many items cost less than 100

import numpy as np

prices = np.array([150, 80, 320, 45, 500, 260, 99])

above_200 = prices[prices > 200]
print("Prices above 200:", above_200)

between_50_300 = prices[(prices >= 50) & (prices <= 300)]
print("Prices between 50 and 300:", between_50_300)

less_than_100 = np.sum(prices < 100)
print("Count of items costing less than 100:", less_than_100)

Prices above 200: [320 500 260]
Prices between 50 and 300: [150  80 260  99]
Count of items costing less than 100: 3


In [ ]:
import numpy as np

exam = np.array([[55, 70, 80],
                 [40, 90, 65],
                 [30, 75, 85]])


print(exam[1,0])
print(exam[0])
print(exam[1,2])
print(exam[exam>=70])

40
[55 70 80]
65
[70 80 90 75 85]


In [13]:
# sales = [1200, 450, 890, 2300, 670, 1800, 300, 950]
# a) Select sales above the average (use np.mean)
# b) Replace all sales below 500 with 0 (use boolean assignment)
# c) Print the modified array

import numpy as np

sales = np.array([1200, 450, 890, 2300, 670, 1800, 300, 950])

avg_sales = np.mean(sales)

above_avg = sales[sales > avg_sales]
print("Sales above average:", above_avg)
print("Average sales:", avg_sales)

sales[sales < 500] = 0
print("Modified array (sales < 500 replaced with 0):", sales)

Sales above average: [1200 2300 1800]
Average sales: 1070.0
Modified array (sales < 500 replaced with 0): [1200    0  890 2300  670 1800    0  950]


In [14]:
# base_salary = [30000, 45000, 60000, 25000]
# Add a 10% raise to all salaries using broadcasting (multiply by 1.1)
# Print original and new salaries

import numpy as np

base_salary = np.array([30000, 45000, 60000, 25000])
new_salary = base_salary * 1.1

print("Original salaries:", base_salary)
print("New salaries (10% raise):", new_salary)

Original salaries: [30000 45000 60000 25000]
New salaries (10% raise): [33000. 49500. 66000. 27500.]


In [15]:
# product_prices = [[100, 200, 300], [400, 500, 600]]
# discount = [10, 20, 30] (discount per column/category)
# Subtract discount from each row of prices using broadcasting
# Print the discounted prices

import numpy as np

product_prices = np.array([[100, 200, 300], 
                           [400, 500, 600]])
discount = np.array([10, 20, 30])

discounted_prices = product_prices - discount
print("Discounted prices:\n", discounted_prices)

Discounted prices:
 [[ 90 180 270]
 [390 480 570]]


In [17]:
# celsius = [0, 10, 20, 30, 37, 100]
# Convert all to Fahrenheit using broadcasting: F = (C * 9/5) + 32
# Print both arrays

import numpy as np

celsius = np.array([0, 10, 20, 30, 37, 100])
fahrenheit = (celsius * 9/5) + 32

print("Celsius:", celsius)
print("Fahrenheit:", fahrenheit)

Celsius: [  0  10  20  30  37 100]
Fahrenheit: [ 32.   50.   68.   86.   98.6 212. ]


In [18]:
# distance_km = [[5, 10, 15], [20, 25, 30]]
# speed_kmph = [50, 60, 80] (one speed per column)
# Calculate time (hours) = distance / speed using broadcasting
# Print the time matrix

import numpy as np

distance_km = np.array([[5, 10, 15],
                        [20, 25, 30]])
speed_kmph = np.array([50, 60, 80])

time_hours = distance_km / speed_kmph
print("Time (hours) matrix:\n", time_hours)

Time (hours) matrix:
 [[0.1        0.16666667 0.1875    ]
 [0.4        0.41666667 0.375     ]]


In [19]:
# weights = [55.7, 72.3, 68.9, 80.1, 61.4]
# a) Print the dtype
# b) Cast to int32 and print
# c) Cast to float16 and print

import numpy as np

weights = np.array([55.7, 72.3, 68.9, 80.1, 61.4])
print("Original dtype:", weights.dtype)

weights_int32 = weights.astype(np.int32)
print("Cast to int32:", weights_int32)

weights_float16 = weights.astype(np.float16)
print("Cast to float16:", weights_float16)

Original dtype: float64
Cast to int32: [55 72 68 80 61]
Cast to float16: [55.7 72.3 68.9 80.1 61.4]


In [20]:
# votes = [1, 0, 1, 1, 0, 0, 1] (1=yes, 0=no)
# a) Cast to bool and print
# b) Count total 'yes' votes using np.sum()
# c) Cast the bool array back to int and print

import numpy as np

votes = np.array([1, 0, 1, 1, 0, 0, 1])
votes_bool = votes.astype(bool)
print("Cast to bool:", votes_bool)

total_yes = np.sum(votes_bool)
print("Total 'yes' votes:", total_yes)

votes_back_to_int = votes_bool.astype(int)
print("Cast back to int:", votes_back_to_int)

Cast to bool: [ True False  True  True False False  True]
Total 'yes' votes: 4
Cast back to int: [1 0 1 1 0 0 1]


In [21]:
# prices_str = np.array(['10.5', '20.0', '30.75', '15.25']) dtype is string
# a) Cast to float64 and print
# b) Cast that float array to int and print (observe the truncation)

import numpy as np

prices_str = np.array(['10.5', '20.0', '30.75', '15.25'])
print("Original dtype:", prices_str.dtype)

prices_float = prices_str.astype(np.float64)
print("Cast to float64:", prices_float)

prices_int = prices_float.astype(int)
print("Cast to int (truncated):", prices_int)

Original dtype: <U5
Cast to float64: [10.5  20.   30.75 15.25]
Cast to int (truncated): [10 20 30 15]


In [22]:
# exam_marks = [45.9, 78.3, 92.7, 33.1, 60.5]
# a) Cast to int (observe what happens to decimals)
# b) Use np.round() first, THEN cast to int
# c) Print both and explain the difference

import numpy as np

exam_marks = np.array([45.9, 78.3, 92.7, 33.1, 60.5])

# Direct cast to int (truncates decimals)
marks_direct_int = exam_marks.astype(int)
print("Direct cast to int (truncated):", marks_direct_int)

# Round first, then cast to int
marks_rounded_int = np.round(exam_marks).astype(int)
print("Round first then cast to int:", marks_rounded_int)

print("\nExplanation: Direct casting truncates decimals (floor towards zero),")
print("while rounding first gives the nearest integer value.")

Direct cast to int (truncated): [45 78 92 33 60]
Round first then cast to int: [46 78 93 33 60]

Explanation: Direct casting truncates decimals (floor towards zero),
while rounding first gives the nearest integer value.


In [23]:
# students = 5 students with marks in 3 subjects each (create a 5x3 array)
# Calculate total marks per student (use np.sum with axis=1)
# Calculate average marks per student

import numpy as np

# 5 students, 3 subjects (Math, Physics, Chemistry)
marks = np.array([
    [85, 90, 78],
    [72, 88, 84],
    [91, 85, 89],
    [68, 75, 70],
    [95, 92, 88]
])

total_per_student = np.sum(marks, axis=1)
average_per_student = np.mean(marks, axis=1)

print("Marks array (5 students × 3 subjects):\n", marks)
print("\nTotal marks per student:", total_per_student)
print("Average marks per student:", average_per_student)

Marks array (5 students × 3 subjects):
 [[85 90 78]
 [72 88 84]
 [91 85 89]
 [68 75 70]
 [95 92 88]]

Total marks per student: [253 244 265 213 275]
Average marks per student: [84.33333333 81.33333333 88.33333333 71.         91.66666667]


In [24]:
# initial_investment = [1000, 2000, 5000, 800]
# annual_return_rate = [0.08, 0.12, 0.05, 0.15]
# Calculate value after 1 year: value = investment * (1 + rate)
# Calculate profit = value - initial_investment

import numpy as np

initial_investment = np.array([1000, 2000, 5000, 800])
annual_return_rate = np.array([0.08, 0.12, 0.05, 0.15])

value_after_1_year = initial_investment * (1 + annual_return_rate)
profit = value_after_1_year - initial_investment

print("Initial investment:", initial_investment)
print("Annual return rate:", annual_return_rate)
print("Value after 1 year:", value_after_1_year)
print("Profit:", profit)

Initial investment: [1000 2000 5000  800]
Annual return rate: [0.08 0.12 0.05 0.15]
Value after 1 year: [1080. 2240. 5250.  920.]
Profit: [ 80. 240. 250. 120.]


In [25]:
# speed_ms = [10, 25, 5, 18, 30] (meters per second)
# Convert to km/h: multiply by 3.6
# Find: max speed, min speed, average speed in km/h

import numpy as np

speed_ms = np.array([10, 25, 5, 18, 30])
speed_kmh = speed_ms * 3.6

print("Speed in m/s:", speed_ms)
print("Speed in km/h:", speed_kmh)
print("Maximum speed (km/h):", np.max(speed_kmh))
print("Minimum speed (km/h):", np.min(speed_kmh))
print("Average speed (km/h):", np.mean(speed_kmh))

Speed in m/s: [10 25  5 18 30]
Speed in km/h: [ 36.   90.   18.   64.8 108. ]
Maximum speed (km/h): 108.0
Minimum speed (km/h): 18.0
Average speed (km/h): 63.36


In [29]:
# A = [[2,3],[4,5]] B = [[1,2],[3,4]]
# a) Element-wise multiply A * B
# b) Element-wise A ** 2
# c) np.dot(A, B) — matrix multiplication (observe the difference)

import numpy as np

A = np.array([[2, 3], [4, 5]])
B = np.array([[1, 2], [3, 4]])

elementwise_multiply = A * B
print("Element-wise multiplication (A * B):\n", elementwise_multiply)

elementwise_square = A ** 2
print("\nElement-wise square (A ** 2):\n", elementwise_square)

matrix_multiply = np.dot(A, B)
print("\nMatrix multiplication (np.dot(A, B)):\n", matrix_multiply)

print("\nDifference: Element-wise multiplies corresponding elements,")
print("while matrix multiplication follows linear algebra rules.")


# hypotenuse: for a right triangle, c = sqrt(a^2 + b^2)
# a_sides = [3, 5, 8, 6]
# b_sides = [4, 12, 15, 8]
# Calculate all hypotenuses using np.sqrt()

import numpy as np

a_sides = np.array([3, 5, 8, 6])
b_sides = np.array([4, 12, 15, 8])

hypotenuses = np.sqrt(a_sides**2 + b_sides**2)
print("Side a:", a_sides)
print("Side b:", b_sides)
print("Hypotenuse (c):", hypotenuses)

# population = [100, 200, 400, 800, 1600] (doubles each step)
# a) Apply np.log2() to find doubling steps
# b) Apply np.log() (natural log) and print
# c) What is np.exp(np.log(population))? Print and explain.

import numpy as np

population = np.array([100, 200, 400, 800, 1600])

log2_pop = np.log2(population)
print("log2(population):", log2_pop)

log_pop = np.log(population)
print("log(population) (natural log):", log_pop)

exp_log_pop = np.exp(log_pop)
print("exp(log(population)):", exp_log_pop)

print("\nExplanation: exp(log(population)) returns the original population")
print("because exp() and log() are inverse functions.")

# exam_scores = [[45, 78, 92], [33, 88, 61], [70, 55, 80]]
# a) Find max score in each row (axis=1)
# b) Find min score in each column (axis=0)
# c) Find overall mean
# d) Find standard deviation using np.std()

import numpy as np

exam_scores = np.array([[45, 78, 92],
                        [33, 88, 61],
                        [70, 55, 80]])

max_per_row = np.max(exam_scores, axis=1)
print("Max score in each row:", max_per_row)

min_per_column = np.min(exam_scores, axis=0)
print("Min score in each column:", min_per_column)

overall_mean = np.mean(exam_scores)
print("Overall mean:", overall_mean)

std_dev = np.std(exam_scores)
print("Standard deviation:", std_dev)

# Implement the Sigmoid function (used in neural networks): sigmoid = 1 / (1 + np.exp(-x))
# x = [-3, -1, 0, 1, 3]
# a) Compute sigmoid for all values using np.exp()
# b) Print rounded to 3 decimal places
# c) What do you observe about the output range?

import numpy as np

x = np.array([-3, -1, 0, 1, 3])

sigmoid = 1 / (1 + np.exp(-x))
print("Sigmoid values (rounded to 3 decimals):", np.round(sigmoid, 3))

print("\nObservations about the output range:")
print("- All values are between 0 and 1")
print("- Negative inputs produce values close to 0")
print("- Positive inputs produce values close to 1")
print("- Zero input produces exactly 0.5")
print("- This makes sigmoid useful for binary classification")


Element-wise multiplication (A * B):
 [[ 2  6]
 [12 20]]

Element-wise square (A ** 2):
 [[ 4  9]
 [16 25]]

Matrix multiplication (np.dot(A, B)):
 [[11 16]
 [19 28]]

Difference: Element-wise multiplies corresponding elements,
while matrix multiplication follows linear algebra rules.
Side a: [3 5 8 6]
Side b: [ 4 12 15  8]
Hypotenuse (c): [ 5. 13. 17. 10.]
log2(population): [ 6.64385619  7.64385619  8.64385619  9.64385619 10.64385619]
log(population) (natural log): [4.60517019 5.29831737 5.99146455 6.68461173 7.37775891]
exp(log(population)): [ 100.  200.  400.  800. 1600.]

Explanation: exp(log(population)) returns the original population
because exp() and log() are inverse functions.
Max score in each row: [92 88 80]
Min score in each column: [33 55 61]
Overall mean: 66.88888888888889
Standard deviation: 18.811606608949607
Sigmoid values (rounded to 3 decimals): [0.047 0.269 0.5   0.731 0.953]

Observations about the output range:
- All values are between 0 and 1
- Negative inputs p