# Introduction to NumPy
**R.A : Muhammad Huzifa**

## Hour 1 — Introduction to NumPy

NumPy (Numerical Python) is a library for fast numerical operations using arrays called `ndarray`.

In [ ]:
import numpy as np
print(np.__version__)

**NumPy vs Python list — speed comparison:**

In [2]:
import numpy as np
import time

# 1 Million elements create karein
py_list  = list(range(1000000))
np_array = np.arange(1000000)

# --- Python List Timing ---
start = time.time()
result_list = [x * 2 for x in py_list] # Har element par loop chal raha hai
list_time = time.time() - start

# --- NumPy Array Timing ---
start = time.time()
result_array = np_array * 2 # Direct Vectorized operation (Bohot fast!)
array_time = time.time() - start

print(f'Python list : {list_time:.4f}s')
print(f'NumPy array : {array_time:.4f}s')

# Performance comparison
speed_diff = list_time / array_time
print(f'🚀 NumPy is {speed_diff:.1f}x faster than Python List!')

Python list : 0.0713s
NumPy array : 0.0038s
🚀 NumPy is 18.7x faster than Python List!


### Practice Exercises — Hour 1 (4 exercises)

In [4]:
# Exercise 1
# Import numpy and print its version
import numpy as np
print(np.__version__)

2.4.3


In [6]:
# Exercise 2
# Create a Python list of 5 student marks and convert it into a NumPy array
# Print both and compare their types
import numpy as np

marks = [50, 60, 70, 80, 90]
num = np.array(marks)

print("Array:", num)
print("Type:", type(num)) # Ye check karne ke liye ki ye numpy array hai

Array: [50 60 70 80 90]
Type: <class 'numpy.ndarray'>


In [14]:
# Exercise 3
# Compare speed of multiplying 500,000 elements using Python list vs NumPy array
import numpy as np
import time

py_li = list(range(10000))
np_array = np.arange(10000)

# Python List Calculation
start = time.time()
result = [x * 4 for x in py_li]
# Yahan 'last.time()' ki jagah 'time.time()' hona chahiye
list_duration = time.time() - start 

print(f"Python list took: {list_duration:.6f} seconds")

start=time.time()
result_np=np_array*4
last=time.time()-start
print(f"duration of numpy",last)




# Data create karein (10,000 elements)
py_li = list(range(10000))
np_array = np.arange(10000)

# 1. Python List ka time
start = time.time()
result_list = [x * 4 for x in py_li]
list_time = time.time() - start

# 2. NumPy Array ka time 
start = time.time()
result_np = np_array * 4
numpy_time = time.time() - start

print(f"Duration of Python List: {list_time:.6f}s")
print(f"Duration of NumPy Array: {numpy_time:.6f}s")

# Kitna guna fast hai?
print(f"🚀 NumPy is {list_time/numpy_time:.1f}x faster!")




temp=np.linspace(1,2,20)
print(temp)




Python list took: 0.001417 seconds
duration of numpy 0.0006906986236572266
Duration of Python List: 0.000952s
Duration of NumPy Array: 0.000129s
🚀 NumPy is 7.3x faster!
[1.         1.05263158 1.10526316 1.15789474 1.21052632 1.26315789
 1.31578947 1.36842105 1.42105263 1.47368421 1.52631579 1.57894737
 1.63157895 1.68421053 1.73684211 1.78947368 1.84210526 1.89473684
 1.94736842 2.        ]


In [17]:
# Exercise 4
# Create a NumPy array of temperatures [36.5, 37.1, 36.8, 37.4, 38.0]
temp=np.array( [36.5, 37.1, 36.8, 37.4, 38.0])
print(type(np.array))
# Print the array and its data type


<class 'builtin_function_or_method'>


---
## Hours 2-3-4 — Creating NumPy Arrays
### Part A: From Python Lists

`np.array()` converts a Python list into a NumPy array — works for 1D and 2D.

In [2]:
import numpy as np
scores_1d = np.array([85, 90, 78, 95, 88])
print('1D array:', scores_1d)
print('Type    :', type(scores_1d))

1D array: [85 90 78 95 88]
Type    : <class 'numpy.ndarray'>


In [19]:
marks_2d = np.array([[90, 85, 78],
                     [88, 92, 80],
                     [70, 75, 95]])
print('2D array:\n', marks_2d)

2D array:
 [[90 85 78]
 [88 92 80]
 [70 75 95]]


In [20]:
float_arr = np.array([1.5, 2.7, 3.3, 4.1])
print('Float array:', float_arr)
print('dtype      :', float_arr.dtype)

Float array: [1.5 2.7 3.3 4.1]
dtype      : float64


### Practice Exercises — From Lists (4 exercises)

In [21]:
# Exercise 1
# Create a 1D NumPy array of 6 product prices and print it
products=np.array([1200,300,65.0,7800,800,640])
print(products)



[1200.  300.   65. 7800.  800.  640.]


In [ ]:
# Exercise 2
# Create a 2D NumPy array representing a 3x3 multiplication table
array=np.arange(1,5)
multiplication=array.reshape(4,1)*array
print(multiplication)
number=multiplication
print(number)




[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]
12


In [ ]:
# Exercise 3
# Create a NumPy array from a mixed list [1, 2, 3.5, 4]
# Check what dtype NumPy assigns automatically




In [28]:
# Exercise 4
# Create a 2D array of shape (4, 2) representing 4 students with math and science marks
array=np.array([
    [60,80],
    [60,80],
    [60,80],
    [60,80]

])
shape=array.shape
print(shape)


(4, 2)


---
### Part B: Built-in Methods

`np.zeros()`, `np.ones()`, `np.arange()`, `np.linspace()`, `np.eye()`, `np.full()` — create arrays without typing values.

In [ ]:
print(np.zeros(5))
# print(np.ones((2, 3)))
# print(np.arange(1, 11))
# print(np.linspace(0, 1, 5))

[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[ 1  2  3  4  5  6  7  8  9 10]
[0.   0.25 0.5  0.75 1.  ]


In [30]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [31]:
print(np.full((3, 3), 7))

[[7 7 7]
 [7 7 7]
 [7 7 7]]


### Practice Exercises — Built-in Methods (4 exercises)

In [34]:
# Exercise 1
# Create a 4x4 array of zeros simulating an empty score table
zeros=(np.full((4,4),0))
print(zeros)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [36]:
# Exercise 2
# Create an array of roll numbers from 1 to 30 using arange()
rollnumbers=np.arange(1,31)
print(rollnumbers)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]


In [37]:
# Exercise 3
# Create 8 equally spaced temperature values between 20 and 100 using linspace()
temp=np.linspace(20,100,8)
print(temp)

[ 20.          31.42857143  42.85714286  54.28571429  65.71428571
  77.14285714  88.57142857 100.        ]


In [ ]:
# Exercise 4
# Create a 3x3 array completely filled with the value 99 using np.full()
# value=(np.full((3,3),99))
# print(value)
zeros=(np.full((3,3),99))
print(zeros)

[[99 99 99]
 [99 99 99]
 [99 99 99]]


---
### Part C: Random Arrays

`np.random` module generates random arrays — used for testing, simulations, and data science.

In [43]:
np.random.seed(42)

print(np.random.rand(5))
print(np.random.randint(40, 100, 6))
print(np.random.randn(4))

[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
[58 62 50 50 63 92]
[ 1.57921282  0.76743473 -0.46947439  0.54256004]


In [44]:
np.random.seed(42)
random_2d = np.random.randint(50, 100, (3, 4))
print('Random 2D marks table:\n', random_2d)

Random 2D marks table:
 [[88 78 64 92]
 [57 70 88 68]
 [72 60 60 73]]


### Practice Exercises — Random Arrays (4 exercises)

In [ ]:
# Exercise 1
# Generate a random array of 10 exam scores between 50 and 100 using randint()

scores = np.random.randint(50, 101, size=10)

print(scores)


[85 89 73 52 71 51 73 93 79 87]


In [48]:
# Exercise 2
# Create a 4x4 random matrix of float values between 0 and 1 using rand()
np.random.seed(10)
random=np.random.rand(4,4)
print(random)



# Seed set karte hain taaki result same aaye


[[0.77132064 0.02075195 0.63364823 0.74880388]
 [0.49850701 0.22479665 0.19806286 0.76053071]
 [0.16911084 0.08833981 0.68535982 0.95339335]
 [0.00394827 0.51219226 0.81262096 0.61252607]]


In [51]:
# Exercise 3
# Use seed(10) and generate 5 random numbers twice — confirm both outputs are identical
np.random.seed(5)
random=np.random.rand(4,4)
print(random)




[[0.22199317 0.87073231 0.20671916 0.91861091]
 [0.48841119 0.61174386 0.76590786 0.51841799]
 [0.2968005  0.18772123 0.08074127 0.7384403 ]
 [0.44130922 0.15830987 0.87993703 0.27408646]]


In [53]:
# Exercise 4
# Simulate 7 daily body temperatures using randn() scaled around 36.5
# Hint: 36.5 + 0.3 * np.random.randn(7)


# Seed set karte hain taaki result fix rahe
np.random.seed(42)

# Temperature generate karna
temps = 36.5 + 0.3 * np.random.randn(7)

print(temps)


[36.64901425 36.45852071 36.69430656 36.95690896 36.42975399 36.42975891
 36.97376384]


---
## Array Attributes and Methods

`shape`, `dtype`, `size`, `ndim` inspect the array. `reshape()`, `max()`, `min()`, `argmax()`, `argmin()` transform or analyze.

In [54]:
arr = np.array([[10, 20, 30, 40],
                [50, 60, 70, 80],
                [90, 15, 25, 35]])

print('shape :', arr.shape)
print('dtype :', arr.dtype)
print('size  :', arr.size)
print('ndim  :', arr.ndim)

shape : (3, 4)
dtype : int64
size  : 12
ndim  : 2


In [55]:
reshaped = arr.reshape(4, 3)
print('Reshaped to (4, 3):\n', reshaped)

Reshaped to (4, 3):
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 25 35]]


In [56]:
print('max    :', arr.max())
print('min    :', arr.min())
print('argmax :', arr.argmax())
print('argmin :', arr.argmin())

max    : 90
min    : 10
argmax : 8
argmin : 0


### Practice Exercises — Attributes & Methods (4 exercises)

In [57]:
# Exercise 1
# Create a 2D array of marks (5 students x 3 subjects)
# Print shape, size, ndim, and dtype


# 5 students aur 3 subjects ke marks (Randomly generate kar rahe hain)
np.random.seed(42)
marks = np.random.randint(40, 101, size=(5, 3))

print("Marks Array:\n", marks)

# Properties Print karna
print("\nShape:", marks.shape)   # (Rows, Columns)
print("Size:", marks.size)       # Total elements (Rows * Columns)
print("ndim:", marks.ndim)       # Dimensions (2D array hai)
print("dtype:", marks.dtype)     # Data type (Integer)

Marks Array:
 [[ 78  91  68]
 [ 54  82  47]
 [100  60  78]
 [ 97  58  62]
 [ 50  50  63]]

Shape: (5, 3)
Size: 15
ndim: 2
dtype: int32


In [9]:
# Exercise 2
# Create a 1D array of 12 numbers and reshape it into both (3, 4) and (2, 6)
import numpy as np
arr=np.arange(1,13)
reshape=arr.reshape(3,4),arr.reshape(2,6)
print(reshape)




(array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]]), array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]]))


In [21]:
# Exercise 3
# From an array of 8 exam scores, find the highest score using max()
# and find which student (index) got it using argmax()

marks=np.random.randint(1,101 ,size=8)
print(marks)
for index, value in enumerate(marks):
    if value == max(marks):
        print(index,value)    

[41 56 39 81 33 94  6 49]
5 94


In [22]:
# Exercise 4
# Create a 3D array of shape (2, 3, 4) using np.arange()
# Verify ndim, shape, and sizeimport numpy as np

# 2 * 3 * 4 = 24 elements
arr = np.arange(24).reshape(2, 3, 4)

print("Array:\n", arr)
print("\nndim:", arr.ndim)   # Output: 3 (Ye 3D array hai)
print("shape:", arr.shape)   # Output: (2, 3, 4)
print("size:", arr.size)     # Output: 24 (Total elements)


Array:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

ndim: 3
shape: (2, 3, 4)
size: 24


---
## Operations on Arrays
### Copying — copy() vs view()

`copy()` = independent duplicate. `view()` = a linked reference to same data.

In [ ]:
original  = np.array([10, 20, 30, 40, 50])
deep_copy = original.copy()
deep_copy[0] = 999
print('original after copy change:', original)
print('deep_copy                  :', deep_copy)

In [ ]:
original = np.array([10, 20, 30, 40, 50])
shallow  = original.view()
shallow[0] = 999
print('original after view change :', original)
print('shallow view               :', shallow)

### Practice Exercises — Copying (4 exercises)

In [ ]:
# Exercise 1
# Create an array of 5 student scores. Make a copy, change index 2 in the copy,
# and confirm the original is unchanged


In [ ]:
# Exercise 2
# Create an array and a view of it. Change index 0 in the view
# and observe that the original also changes


In [ ]:
# Exercise 3
# Create two copies of the same array, add 10 to one and subtract 10 from the other
# Print all three arrays to confirm they are fully independent


In [ ]:
# Exercise 4
# Check whether a copy and a view share memory using np.shares_memory()


---
### Append and Insert

`np.append()` adds to the end. `np.insert()` adds at a specific index.

In [ ]:
scores = np.array([85, 90, 78, 95])
new_scores = np.append(scores, 88)
print('After append:', new_scores)

In [ ]:
inserted = np.insert(scores, 2, 100)
print('After insert at index 2:', inserted)

In [ ]:
multi_append = np.append(scores, [70, 65, 80])
print('Append multiple values:', multi_append)

### Practice Exercises — Append & Insert (4 exercises)

In [ ]:
# Exercise 1
# Create an array of 5 product prices. Append a new price and print the result


In [ ]:
# Exercise 2
# Roll numbers are [1, 2, 4, 5] — student roll 3 was added late.
# Insert roll number 3 at the correct position


In [ ]:
# Exercise 3
# Append three new exam scores [72, 68, 91] to an existing scores array


In [ ]:
# Exercise 4
# Insert value 0 at both the beginning (index 0) and end of an array using insert()


---
### Sorting Arrays

`np.sort()` returns a sorted copy — the original array is never changed.

In [ ]:
marks = np.array([72, 55, 90, 63, 88, 41, 95])
sorted_asc  = np.sort(marks)
sorted_desc = np.sort(marks)[::-1]
print('Original  :', marks)
print('Ascending :', sorted_asc)
print('Descending:', sorted_desc)

In [ ]:
table = np.array([[30, 10, 20],
                  [90, 50, 70]])
print('Sort each row   :\n', np.sort(table, axis=1))
print('Sort each column:\n', np.sort(table, axis=0))

### Practice Exercises — Sorting (4 exercises)

In [ ]:
# Exercise 1
# Create an array of 8 random exam scores and sort them in ascending order


In [ ]:
# Exercise 2
# Sort an array of 7 product prices from highest to lowest (descending)


In [ ]:
# Exercise 3
# Create a 2D marks table (3 students x 4 subjects) and sort each student's marks in ascending order
# (sort along axis=1)


In [ ]:
# Exercise 4
# Sort the array and prove the original is unchanged by printing both before and after sorting


---
### Removing / Deleting Elements

`np.delete()` removes elements at given indices and returns a new array — original unchanged.

In [ ]:
scores = np.array([85, 90, 78, 95, 88, 62])
after_delete = np.delete(scores, 2)
print('Original        :', scores)
print('Deleted index 2 :', after_delete)

In [ ]:
multi_delete = np.delete(scores, [0, 3, 5])
print('Deleted indices 0, 3, 5:', multi_delete)

In [ ]:
table = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('Delete row 1:\n', np.delete(table, 1, axis=0))
print('Delete col 2:\n', np.delete(table, 2, axis=1))

### Practice Exercises — Deleting (4 exercises)

In [ ]:
# Exercise 1
# Create an array of 6 scores and remove the score at index 4 (student was absent)


In [ ]:
# Exercise 2
# Remove the first and last elements from an array of 8 temperatures


In [ ]:
# Exercise 3
# Create a 3x3 marks table and delete the second row (a student withdrew from class)


In [ ]:
# Exercise 4
# Delete elements at indices [1, 3, 5] from an array of 7 values and print the result


---
### Combining / Concatenating Arrays

`np.concatenate()` joins end-to-end. `np.vstack()` adds rows. `np.hstack()` adds columns.

In [ ]:
class_a = np.array([85, 90, 78])
class_b = np.array([70, 88, 92])
combined = np.concatenate([class_a, class_b])
print('Concatenated:', combined)

In [ ]:
row1 = np.array([[1, 2, 3]])
row2 = np.array([[4, 5, 6]])
print('vstack:\n', np.vstack([row1, row2]))
print('hstack:\n', np.hstack([row1, row2]))

### Practice Exercises — Combining (4 exercises)

In [ ]:
# Exercise 1
# Combine exam scores of Section A [80, 85, 90] and Section B [70, 75, 88] into one array


In [ ]:
# Exercise 2
# Create two 1x3 arrays (two students' marks) and stack them vertically using vstack()
# to create a 2x3 marks table


In [ ]:
# Exercise 3
# Create two 2x2 arrays (math marks and science marks)
# Join them horizontally using hstack() to create a 2x4 combined table


In [ ]:
# Exercise 4
# Concatenate three arrays [1,2], [3,4], [5,6] into one and verify the final shape


---
### Splitting Arrays

`np.split()` needs equal parts. `np.array_split()` handles unequal sizes without error.

In [23]:
students = np.arange(1, 13)
groups = np.split(students, 3)
print('Equal split into 3 groups:')
for i, g in enumerate(groups):
    print(f'  Group {i+1}: {g}')

Equal split into 3 groups:
  Group 1: [1 2 3 4]
  Group 2: [5 6 7 8]
  Group 3: [ 9 10 11 12]


In [ ]:
students_10 = np.arange(1, 11)
groups_unequal = np.array_split(students_10, 3)
print('Unequal split (10 into 3):')
for i, g in enumerate(groups_unequal):
    print(f'  Group {i+1}: {g}')

In [ ]:
table = np.arange(1, 13).reshape(4, 3)
top, bottom = np.vsplit(table, 2)
print('Top half:\n', top)
print('Bottom half:\n', bottom)

### Practice Exercises — Splitting (4 exercises)

In [ ]:
# Exercise 1
# Create an array of 12 roll numbers and split them into 4 equal groups using split()


In [ ]:
# Exercise 2
# Create an array of 10 scores and split into 3 groups using array_split()
# Print each group and note the unequal sizes


In [ ]:
# Exercise 3
# Create a (6, 3) marks table and split it into top and bottom halves using vsplit()


In [ ]:
# Exercise 4
# Create a (3, 6) array and split it into 3 equal parts column-wise using hsplit()
